"""Added credit cards

Revision ID: 56bfdcb2c7f5
Revises: 844d409732e2
Create Date: 2021-12-03 10:16:05.974587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56bfdcb2c7f5'
down_revision = '844d409732e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creditcard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('typ', sa.String(length=20), nullable=False),
    sa.Column('cardnumber', sa.String(length=30), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cardnumber')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('creditcard')
    # ### end Alembic commands ###
