"""Added phone to person

Revision ID: fb85052bea88
Revises: 56bfdcb2c7f5
Create Date: 2021-12-03 10:36:04.848328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb85052bea88'
down_revision = '56bfdcb2c7f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('phone', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'phone')
    # ### end Alembic commands ###
